"""Browser process lifecycle, CDP connection, session isolation, and page registry.

全部浏览器运行态收敛在单一 :data:`_state`(:class:`_BrowserState`)实例中,
关闭/重置只调用 ``_state.reset()``,不再手工清理十余个模块级全局变量。
原单文件模块的包化拆分;本模块再导出全部历史公开名,外部导入路径不变。
"""

from __future__ import annotations

from .cdp import (
    _chrome_executable,
    _normalize_cdp_url,
    _PortHeldByOtherService,
    _probe_cdp,
    _wait_for_cdp,
)
from .core import (
    _browser_session_impl,
    _close_browser_impl,
    _connect_browser_impl,
    _current_page_impl,
    _inject_cookies_impl,
    _last_cdp_endpoint,
    _launch_chrome_impl,
    _list_pages_impl,
    _open_url_impl,
    _reset_viewport_impl,
    _select_page_impl,
    _start_browser_impl,
    browser_session,
    close_browser,
    connect_browser,
    current_page,
    inject_cookies,
    launch_chrome,
    list_pages,
    open_url,
    reset_viewport,
    select_page,
    start_browser,
)
from .downloads import (
    _configure_browser_downloads,
    _persist_download,
    _schedule_download,
    _wait_download_impl,
    _watch_download_context,
    _watch_download_page,
    wait_download,
)
from .login import _browser_login_impl, _recognize_captcha_with_ai, browser_login
from .runjs import RUN_JS_OUTPUT_LIMIT, _run_js_impl, run_js
from .state import (
    _FALLBACK_REGISTRY_LIMIT,
    _action_lock,
    _BrowserState,
    _compact_frame_url,
    _context_id,
    _frame_context_details,
    _frame_details,
    _frame_id,
    _frame_name_url,
    _frame_page_offset,
    _get_page_preference_probe,
    _page_id,
    _page_preference_probe,
    _page_viewport_size,
    _prune_fallback_registry,
    _select_page_object,
    _session_summary,
    _state,
    set_page_preference_probe,
)
from .viewport import (
    _CLIP_LOCK_TOLERANCE_PX,
    _capture_window_bounds,
    _cdp_window_bounds,
    _looks_like_clip_lock,
    _maximize_and_fill_viewport,
    _page_pixel_ratio,
    _read_viewport_or_none,
    _relayout_after_viewport_change,
    _restore_window_and_viewport,
    _same_size,
    _size_candidates,
)

__all__ = [
    "_BrowserState",
    "_state",
    "_action_lock",
    "_page_preference_probe",
    "set_page_preference_probe",
    "_get_page_preference_probe",
    "_FALLBACK_REGISTRY_LIMIT",
    "_prune_fallback_registry",
    "_page_id",
    "_context_id",
    "_frame_id",
    "_frame_name_url",
    "_compact_frame_url",
    "_frame_details",
    "_session_summary",
    "_select_page_object",
    "_page_viewport_size",
    "_frame_context_details",
    "_frame_page_offset",
    "_persist_download",
    "_schedule_download",
    "_wait_download_impl",
    "_watch_download_page",
    "_watch_download_context",
    "_configure_browser_downloads",
    "wait_download",
    "_page_pixel_ratio",
    "_CLIP_LOCK_TOLERANCE_PX",
    "_read_viewport_or_none",
    "_cdp_window_bounds",
    "_same_size",
    "_size_candidates",
    "_looks_like_clip_lock",
    "_capture_window_bounds",
    "_relayout_after_viewport_change",
    "_restore_window_and_viewport",
    "_maximize_and_fill_viewport",
    "_normalize_cdp_url",
    "_chrome_executable",
    "_PortHeldByOtherService",
    "_probe_cdp",
    "_wait_for_cdp",
    "_start_browser_impl",
    "start_browser",
    "_connect_browser_impl",
    "connect_browser",
    "_close_browser_impl",
    "close_browser",
    "_last_cdp_endpoint",
    "_current_page_impl",
    "current_page",
    "_list_pages_impl",
    "list_pages",
    "_select_page_impl",
    "select_page",
    "_browser_session_impl",
    "browser_session",
    "_reset_viewport_impl",
    "reset_viewport",
    "_open_url_impl",
    "open_url",
    "_inject_cookies_impl",
    "inject_cookies",
    "_launch_chrome_impl",
    "launch_chrome",
    "_recognize_captcha_with_ai",
    "_browser_login_impl",
    "browser_login",
    "RUN_JS_OUTPUT_LIMIT",
    "_run_js_impl",
    "run_js",
]
